version: "3.9"
services:
  server:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - type: bind
        source: .
        target: /app
  db:
    image: mongo:latest
    restart: always
    volumes:
      - type: volume
        source: db
        target: /data/db
    ports:
      - "8001:27017"
    command: --quiet
volumes:
  db:
