version: "3.9"
services:
  server:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - type: bind
        source: .
        target: /app
  db:
    image: mongo:latest
    restart: always
    volumes:
      - type: volume
        source: db
        target: /data/db
    ports:
      - "8001:${DB_PORT}"
    environment:
      MONGO_INITDB_DATABASE: "${DB_NAME}"
      MONGO_INITDB_ROOT_USERNAME: "${DB_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"
    command: --quiet
volumes:
  db:
