version: "3.9"
services:
  server:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - type: bind
        source: .
        target: /app
    depends_on:
      mongo:
        condition: service_healthy
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - type: volume
        source: data
        target: /data/db
    ports:
      - "8001:${DB_PORT}"
    environment:
      MONGO_INITDB_DATABASE: "${DB_NAME}"
      MONGO_INITDB_ROOT_USERNAME: "${DB_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"
    command: --quiet
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s
volumes:
  data:
